server:
  address: 0.0.0.0  # Bind to all network interfaces for LAN access
  port: 8081
  servlet:
    context-path: /api

spring:
  data:
    mongodb:
      uri: mongodb+srv://balankaswan14:Balan30@brcmanagement.xyhobwb.mongodb.net/transport_management?retryWrites=true&w=majority&appName=BRCMANAGEMENT
  
  application:
    name: transport-management-system

# CORS Configuration for cross-origin requests
cors:
  allowed-origins: "*"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  allow-credentials: false

# Logging Configuration
logging:
  level:
    com.transport.management: DEBUG
    org.springframework.web: DEBUG
    org.springframework.data.mongodb: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Management endpoints for monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,env
      base-path: /actuator
  endpoint:
    health:
      show-details: always
